Repository awslabs/seed-farmer, pull requests merged in 2024-08, with the labels that each got.

#675 fix: adds validation for trusted principal arns in `seedfarmer bootstrap toolchain`
  CHANGELOG.md
  seedfarmer/cli_groups/_bootstrap_group.py
  seedfarmer/commands/_bootstrap_commands.py
  test/unit-test/test_commands_bootstrap.py
Labels: bug

#685 fix: Update trusted principal validation to allow additional aws partitions
  seedfarmer/commands/_bootstrap_commands.py
Labels: bug

#694 release: 5.0.0
  CHANGELOG.md
  VERSION
  setup.py
Labels: release

#695 release: `5.0.0`
  .gitignore
  CHANGELOG.md
  VERSION
  docs/requirements-docs.in
  docs/requirements-docs.txt
  docs/source/architecture.md
  docs/source/manifests.md
  docs/source/upgrades.md
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
  seedfarmer/cli_groups/_bootstrap_group.py
  seedfarmer/cli_groups/_init_group.py
  seedfarmer/commands/_bootstrap_commands.py
  seedfarmer/commands/_deployment_commands.py
  seedfarmer/commands/_module_commands.py
  seedfarmer/commands/_project_policy_commands.py
  seedfarmer/commands/_stack_commands.py
  seedfarmer/mgmt/archive_support.py
  seedfarmer/mgmt/git_support.py
  seedfarmer/mgmt/module_init.py
  seedfarmer/models/manifests/_deployment_manifest.py
  seedfarmer/models/manifests/_module_manifest.py
  seedfarmer/models/transfer/_module_deploy_object.py
  seedfarmer/resources/toolchain_role.template
  seedfarmer/services/_iam.py
  seedfarmer/services/_service_utils.py
  seedfarmer/services/session_manager.py
  seedfarmer/utils.py
  setup.py
  test/unit-test/test_commands_bootstrap.py
  test/unit-test/test_commands_deployment.py
  test/unit-test/test_commands_module.py
  test/unit-test/test_commands_stack.py
  test/unit-test/test_mgmt.py
  test/unit-test/test_mgmt_archive_support.py
  test/unit-test/test_models.py
Labels: release

#689 chore: add badges to readme for version and license
  README.md
Labels: documentation

#696 Latest Development
  VERSION
Labels: release

#697 latest development
  VERSION
Labels: release

#704 docs: Clarify the usage of archiveSecret
  docs/source/manifests.md
Labels: documentation
